name: "✔️ Check Gradle wrapper"

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'gradlew*'
      - 'gradle/wrapper/**'
  pull_request:
    branches:
      - master
    paths:
      - 'gradlew*'
      - 'gradle/wrapper/**'

jobs:
  check-gradle-wrapper:
    name: Check Gradle wrapper
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - name: "Check Gradle wrapper"
        uses: gradle/actions/wrapper-validation@f29f5a9d7b09a7c6b29859002d29d24e1674c884
