name: "✔️ Check Gradle wrapper"

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'gradlew*'
      - 'gradle/wrapper/**'
  pull_request:
    branches:
      - master
    paths:
      - 'gradlew*'
      - 'gradle/wrapper/**'

jobs:
  check-gradle-wrapper:
    name: Check Gradle wrapper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: "Check Gradle wrapper"
        uses: gradle/actions/wrapper-validation@v5
