name: "⬆️ GitHub release -> Homebrew PR"

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  new-update:
    name: Deploy Homebrew
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@63b9213ab301419de3ea477f3f190af01f9a7818
        with:
          token: ${{ secrets.DEPLOY_HOMEBREW_GITHUB_TOKEN }}
      - name: Set up Git
        run: |
          git config --global user.email mail@artemchep.com
          git config --global user.name AChep
      - name: Update Homebrew cask
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.DEPLOY_HOMEBREW_GITHUB_TOKEN }}
        run: |
          brew tap homebrew/cask --force
          brew update
          brew bump --open-pr --casks keyguard
