name: "⬆️ GitHub release -> Scoop deployment"

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  new-update:
    name: Deploy Scoop
    runs-on: ubuntu-slim
    steps:
      - name: "Checkout"
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - name: "Trigger Workflow"
        uses: ./.github/actions/github_trigger_wf
        with:
          github-token: ${{ secrets.PERSONAL_TOKEN }}
          github-wf-repo: AChep/keyguard-repo-scoop
          github-wf-file: excavator.yml
