name: "ðŸ•’ Synchronize Two-factor auth"

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      # Configuration.
      - '.github/update_twofactorauth.py'

jobs:
  sync-2fa:
    name: Synchronize Two-factor authentication
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: "Update library"
        run: |
          python .github/update_twofactorauth.py
      - uses: ./.github/actions/github_submit_pr
        with:
          commit-message: "Update two-factor auth library"
          commit-branch: tfa_2factorauth_action
