name: "ðŸ•’ Synchronize All"

on:
  workflow_dispatch:

jobs:
  sync-all:
    name: Synchronize ${{ matrix.wf-file }}
    runs-on: ubuntu-slim
    strategy:
      fail-fast: false
      matrix:
        wf-file:
          - update_gpm_passkeys_priv_apps.yml
          - update_justdeleteme.yml
          - update_justgetmydata.yml
          - update_localization.yml
          - update_passkeys.yml
          - update_tld.yml
          - update_twofactorauth.yml
    steps:
      - name: "Checkout"
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - name: "Trigger Workflow"
        uses: ./.github/actions/github_trigger_wf
        with:
          github-token: ${{ secrets.PERSONAL_TOKEN }}
          github-wf-file: ${{ matrix.wf-file }}
