name: "ðŸ•’ Synchronize TLD public suffix list"

on:
  workflow_dispatch:

jobs:
  sync-tld:
    name: Synchronize TLD public suffix list
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: "Update data"
        run: |
          wget https://publicsuffix.org/list/public_suffix_list.dat
          mv -f public_suffix_list.dat common/src/commonMain/composeResources/files/public_suffix_list.txt
      - uses: ./.github/actions/github_submit_pr
        with:
          github-token: ${{ secrets.PERSONAL_TOKEN }}
          commit-message: "Update Public suffix list"
          commit-branch: tld_public_suffix_list_action
