name: "ðŸ•’ Synchronize Just get my data"

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      # Configuration.
      - '.github/update_justgetmydata.py'
      - '.github/update_justgetmydata.requirements.txt'

jobs:
  sync-passkeys:
    name: Synchronize Just get my data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: pip install -r .github/update_justgetmydata.requirements.txt
      - name: "Update library"
        run: |
          python .github/update_justgetmydata.py
      - uses: ./.github/actions/github_submit_pr
        with:
          commit-message: "Update justgetmydata library"
          commit-branch: justgetmydata_action
