name: "ðŸ•’ Synchronize Two-factor auth"

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      # Configuration.
      - '.github/update_twofactorauth.py'

jobs:
  sync-2fa:
    name: Synchronize Two-factor authentication
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Update library"
        run: |
          python .github/update_twofactorauth.py
      - name: "Check if any changes"
        id: check-changes
        run: |
          has_changes=$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)
          echo "$has_changes"
          echo "HAS_CHANGES=$has_changes" >> "$GITHUB_OUTPUT"
      - name: Commit and push changes
        uses: devops-infra/action-commit-push@v0.11.2
        if: ${{ startsWith(steps.check-changes.outputs.HAS_CHANGES, 'true') }}
        with:
          github_token: "${{ secrets.PERSONAL_TOKEN }}"
          add_timestamp: false
          commit_prefix: "[AUTO]"
          commit_message: "Update two-factor auth library"
          force: true
          target_branch: tfa_2factorauth_action
      - name: Create pull request
        uses: devops-infra/action-pull-request@v0.6.0
        if: ${{ startsWith(steps.check-changes.outputs.HAS_CHANGES, 'true') }}
        with:
          github_token: "${{ secrets.PERSONAL_TOKEN }}"
          source_branch: tfa_2factorauth_action
          target_branch: master
          assignee: AChep
          label: "robot,enhancement"
          title: New Two-factor auth by GitHub Action
