name: "ðŸ•’ Synchronize GPM Credential Privileged Apps"

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      # Configuration.
      - '.github/update_gpm_passkeys_priv_apps.py'
      - '.github/update_gpm_passkeys_priv_apps.requirements.txt'

jobs:
  sync-gpm-passkeys-priv-apps:
    name: Synchronize GPM Credential Privileged Apps
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
      - run: pip install -r .github/update_gpm_passkeys_priv_apps.requirements.txt
      - name: "Update library"
        run: |
          python .github/update_gpm_passkeys_priv_apps.py
      - uses: ./.github/actions/github_submit_pr
        with:
          commit-message: "Update GPM Credential Privileged Apps JSON"
          commit-branch: gpmpasskeysprivapps_action
