name: "ðŸ•’ Synchronize Just delete me"

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      # Configuration.
      - '.github/update_justdeleteme.py'
      - '.github/update_justdeleteme.requirements.txt'

jobs:
  sync-passkeys:
    name: Synchronize Just delete me
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: pip install -r .github/update_justdeleteme.requirements.txt
      - name: "Update library"
        run: |
          python .github/update_justdeleteme.py
      - uses: ./.github/actions/github_submit_pr
        with:
          commit-message: "Update justdeleteme library"
          commit-branch: justdeleteme_action
